#:kivy 2.1.0
#:import menu src.menu.menu

MainWidget:
    canvas.before:
        Rectangle:
            size: self.size
            source: 'images/bg.jpg'
    menu_widget: menu_widget
    perspective_point_x: self.width / 2
    perspective_point_y: self.height * 0.75
    Label:
        text: root.score
        font_size: dp(30)
        font_name: 'fonts/WarsawGothic.ttf'
        size_hint: .16, .16
        pos_hint: {"x": 0, "top": 1}
    MenuWidget:
        id: menu_widget